# JupyterHub docker compose configuration file

services:
  hub:
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
      args:
        JUPYTERHUB_VERSION: latest
    restart: always
    image: jupyterhub
    container_name: jupyterhub
    networks:
      - jupyterhub-network
    volumes:
      # The JupyterHub configuration file
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "jupyterhub-data:/data"
    ports:
      - "8001:8000"
      - "9000:9000"
    environment:
      # This username will be a JupyterHub admin
      JUPYTERHUB_ADMIN: admin
      # All containers will join this network
      DOCKER_NETWORK_NAME: jupyterhub-network
      # JupyterHub will spawn this Notebook image for users
      # DOCKER_NOTEBOOK_IMAGE: quay.io/jupyter/base-notebook:latest
      DOCKER_NOTEBOOK_IMAGE: user-notebook
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: /home/jovyan/work
      # Default startup notebook, must start with /lab/tree
      # The notebook should be in the user's home directory, see the Dockerfile in user-notebook
      DEFAULT_NOTEBOOK: /lab/tree/Welcome.ipynb

  user-notebook:
    build:
      context: ./user-notebook
      dockerfile: Dockerfile
      args:
        - CHAT_DIR=chats
    environment:
      - CHAT_DIR=chats
    image: user-notebook
    networks:
      - jupyterhub-network

  middleware:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    image: middleware
    container_name: middleware
    networks:
      - jupyterhub-network
    volumes:
      - "middleware-data:/var/log/jelai"
      - "chat-histories:/app/chat_histories"
      - "./middleware/inputs:/app/inputs:rw"
    ports:
      - "24224:24224"
      - "8004:8004" 
      - "8003:8003"
      - "8005:8005"
    depends_on:
      - hub

  admin-dashboard:
    build:
      context: ./admin-dashboard
      dockerfile: Dockerfile
    image: admin-dashboard
    container_name: admin-dashboard
    networks:
      - jupyterhub-network
    volumes:
      - "./middleware/inputs:/app/inputs:rw"
      - "chat-histories:/app/chat_histories:ro"
      - "middleware-data:/app/logs:ro"
      - "./user-notebook/learning_materials:/app/learning_materials:rw"
      - "jupyterhub-data:/app/jupyterhub_data:ro"
    ports:
      - "8006:8006"
    depends_on:
      - middleware
    environment:
      - MIDDLEWARE_URL=http://middleware:8005
      - JUPYTERHUB_URL=http://hub:8000

volumes:
  jupyterhub-data:
  middleware-data:
  chat-histories:

networks:
  jupyterhub-network:
    name: jupyterhub-network
    driver: bridge
