# JupyterHub docker compose configuration file

services:
  hub:
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
      args:
        JUPYTERHUB_VERSION: latest
    restart: always
    image: jupyterhub
    container_name: jupyterhub
    networks:
      - jupyterhub-network
    volumes:
      # The JupyterHub configuration file
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "jupyterhub-data:/data"
      # Workspace templates and shared resources
      - "workspace-templates:/srv/jupyterhub/workspace_templates"
      - "shared-resources:/srv/jupyterhub/shared_resources"
    ports:
      - "8001:8000"
      - "9000:9000"
    environment:
      # This username will be a JupyterHub admin
      JUPYTERHUB_ADMIN: admin
      # All containers will join this network
      DOCKER_NETWORK_NAME: jupyterhub-network
      # JupyterHub will spawn this Notebook image for users
      # DOCKER_NOTEBOOK_IMAGE: quay.io/jupyter/base-notebook:latest
      DOCKER_NOTEBOOK_IMAGE: user-notebook
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: /home/jovyan/work
      # Default startup notebook, must start with /lab/tree
      # The notebook should be in the user's home directory, see the Dockerfile in user-notebook
      DEFAULT_NOTEBOOK: /lab/tree/Welcome.ipynb
      # Shared service token for learn-dashboard proxied service
      LEARN_DASHBOARD_TOKEN: ${LEARN_DASHBOARD_TOKEN}

  user-notebook:
    build:
      context: ./user-notebook
      dockerfile: Dockerfile
      args:
        - CHAT_DIR=chats
    environment:
      - CHAT_DIR=chats
    image: user-notebook
    networks:
      - jupyterhub-network

  middleware:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    image: middleware
    container_name: middleware
    networks:
      - jupyterhub-network
    volumes:
      - "middleware-data:/var/log/jelai"
      - "courses-data:/app/data"
      - "chat-histories:/app/chat_histories"
      - "./middleware/inputs:/app/inputs:rw"
      - "learning-materials:/app/learning_materials:rw"
      - "workspace-templates:/app/workspace_templates:rw"
      - "shared-resources:/app/shared_resources:rw"
      - "learning-objectives:/app/learning_objectives:rw"
      # Mount the project directory for configuration access
      - ".:/app/jupyterhub-docker:ro"
    ports:
      - "24224:24224"
      - "8004:8004" 
      - "8003:8003"
      # Port 8005 admin API is now internal only - accessed via admin dashboard
    depends_on:
      - hub
    environment:
      - COURSES_DATA_DIR=/app/data

  admin-dashboard:
    build:
      context: ./admin-dashboard
      dockerfile: Dockerfile
    image: admin-dashboard
    container_name: admin-dashboard
    networks:
      - jupyterhub-network
    volumes:
      - "./middleware/inputs:/app/inputs:rw"
      - "chat-histories:/app/chat_histories:ro"
      - "middleware-data:/app/logs:ro"
      - "learning-materials:/app/learning_materials:rw"
      - "jupyterhub-data:/app/jupyterhub_data:ro"
      - "workspace-templates:/app/workspace_templates:rw"
      - "shared-resources:/app/shared_resources:rw"
      - "learning-objectives:/app/learning_objectives:rw"
    environment:
      - JUPYTERHUB_API_URL=http://jupyterhub:8080
      - JUPYTERHUB_API_TOKEN=${LEARN_DASHBOARD_TOKEN}
      - JUPYTERHUB_CLIENT_ID=service-learn-dashboard
      - JUPYTERHUB_SERVICE_PREFIX=/services/learn-dashboard
      - MIDDLEWARE_URL=http://middleware:8005
      - LEARN_DASHBOARD_TOKEN=${LEARN_DASHBOARD_TOKEN}
    ports:
      - "8006:8006"

volumes:
  jupyterhub-data:
  jupyterhub-db-data:
  middleware-data:         # Middleware logs and data
  chat-histories:          # Chat database storage
  learning-materials:      # Shared learning materials
  workspace-templates:     # Individual files copied to each student
  shared-resources:        # Read-only shared files mounted for all
  learning-objectives:     # Learning objectives storage
  courses-data:            # Persisted courses and enrollments

networks:
  jupyterhub-network:
    name: jupyterhub-network
    driver: bridge
